# Generated by Django 5.2.6 on 2025-09-26 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correntista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_correntista', models.CharField(max_length=50)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacao', models.CharField(choices=[('C', 'Crédito'), ('D', 'Débito')], max_length=1)),
                ('valor_operacao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_operacao', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(max_length=50)),
                ('correntista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='core.correntista')),
                ('correntista_beneficiario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_recebidas', to='core.correntista')),
            ],
        ),
    ]
